n1 = int (input ('digite um número '))
n2 = int (input('digite mais um número '))
s = (n1+n2)
print ('a soma entre os valores vale {}' .format(s))

a = input ('digite algo: ')
print('o tipo primitivo desse valor é ', type(a))
print('só tem espaços? ', a.isspace())
print('só tem número? ', a.isnumeric())
print('é alfabético? ', a.isalpha())
print('é alfanumérico?', a.isalnum())
print('está em minusculo?', a.islower())
print('está em maiúsculo?', a.isupper())
print('está capitalizada?', a.istitle())
print('está em dicimal?',a.isdecimal())
